apiVersion: apps/v1
kind: Deployment
metadata:
  name: felhohf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: felhohf
  template:
    metadata:
      labels:
        app: felhohf
    spec:
      containers:
      - name: felhohf
        image: sandorbalu/felhohf:{{ .Values.env.APP_VERSION }}
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: rootpassword
        - name: DB_NAME
          value: image_service
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: felhohf-service
spec:
  type: NodePort
  selector:
    app: felhohf
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # << valid NodePort between 30000–32767
