apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: sandorbalu/felhohf:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mysql-db
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: rootpassword
            - name: DB_NAME
              value: image_service
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: php-app
