apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-php-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-php-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-php-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-php-app.name" . }}
    spec:
      containers:
        - name: my-php-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql-service"  # Change this if you're using a different DB service name
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "example"  # Modify this for your DB password
            - name: DB_NAME
              value: "image_service"
